Reliability part2
conwayste/netwayste pull request #6
Opened 2018-09-12 04:47 UTC by Manghi

I like keeping these PR's small so here's another. This one is just to keep things structured nice, tidy, and reusable.

Part two primarily includes:
- Create types for netwayste packet buffering
  - `ItemQueue<T>` is a `VecDeque<T>`
- Traits~!
  - `NetworkQueue<T>` describes the basic functionality needed for a transmit or receive network queue
  - `TXQueue<T>` implements `NetworkQueue<T>` for transmission-related actions
   - `RXQueue<T>` implements `NetworkQueue<T>` for receiving-related actions
- RX queues can work for any type T, as long as T is bound to `Sequenced`. 
  - This means we now have `RXQueue<Packet>` and `RXQueue<BroadcastChatMessages>` and the handling of them uses the exact same infrastructure!! (Yay no code duplication which was where I was headed at first)
- `Sequenced` is a trait which adds ordering to custom types, by comparing internal sequence numbers
  - For packets, this is their packet sequence number
  - For Updates, this would be the chat messages' sequence number
  - This is the crux in which ordering is determined when searching through a buffer for the insertion index
- General refactoring to ensure the surrounding code/comments actually make sense
- Few more unit tests

2018-09-22 20:54 UTC, AaronM04 commented
@Manghi It looks like ticks happen 100x more often than they need to, and 99% of the time nothing gets run:

```rust
if (server_state.tick % 100) == 0
```
Maybe we could just remove that `if` block and decrease the frequency of the ticks?

2018-09-24 00:50 UTC, Manghi commented
> 
> 
> @Manghi It looks like ticks happen 100x more often than they need to, and 99% of the time nothing gets run:
> 
> ```rust
> if (server_state.tick % 100) == 0
> ```
> 
> Maybe we could just remove that `if` block and decrease the frequency of the ticks?

Yeah I'm aware of that, same thing happens in `client.rs`. Intention was to address them both in part three when I add in another future stream. Up to you if you want me to fix it in this PR or part 3.

2018-09-28 02:26 UTC, AaronM04 requested changes

2018-09-28 02:26 UTC, AaronM04 commented on src/net.rs
> +    /// Small note: The splitting of VecDequeue is into its 'front' and 'back' halves, based on how 'push_front' and 'push_back' were used.
This is a very long line. Please split up!

2018-09-28 02:26 UTC, AaronM04 commented on src/net.rs
> +    /// Primarily, they cover the cases where out-of-order insertion would transition the queue into a wrapped state from a non-wrapped state.
2 very long lines

2018-09-28 02:26 UTC, AaronM04 commented on src/net.rs
> +    fn is_seq_about_to_wrap(&self, buffer_wrap_index: Option<usize>, sequence: u64, oldest_seq_num: u64, newest_seq_num: u64) -> bool {
Please wrap this long line...

2018-09-28 02:26 UTC, AaronM04 commented on src/net.rs
> +pub trait NetworkQueue<T: Ord+Sequenced> {
:skull: does not compile! Error on this line because `Sequenced` is not defined.
Rest of this review will omit latest commit. :skull_and_crossbones:

2018-09-28 02:26 UTC, AaronM04 commented on src/net.rs
> +    /// `rx_buffer_wrap_index` is maintained to denote the queue index at which the numerical wrap occurs.
`rx_buffer_wrap_index` isn't defined anywhere. I think you meant `buffer_wrap_index`

2018-09-28 02:26 UTC, AaronM04 commented on src/net.rs
> +    fn is_seq_sufficiently_far_away(&self, a: u64, b: u64) -> bool {
I think it would be cleaner to avoid requiring that `a >= b`. Why not have `mut a: u64` and `mut b: u64` in the argument list and then swap them if `a < b`? Then you can simplify `is_seq_about_to_wrap` and other usages of this function. :smile:

2018-09-28 02:26 UTC, AaronM04 commented on src/net.rs
> +    /// Sequence must be >=, or <, what we're comparing against. Cannot have wrapped yet.
`Sequence must be >=, or <, what we're comparing against.`
Aren't those the only two possibilities? :smile:

2018-09-28 02:50 UTC, AaronM04 commented on src/net.rs
> +                        self.buffer_wrap_index = Some(buffer_wrap_index - 1);
Case is not hit by any unit test.

2018-09-28 03:05 UTC, AaronM04 commented on src/net.rs
> +                self.push_front(item);
Dead code.

2018-09-28 03:13 UTC, AaronM04 commented on src/net.rs
> +            let insertion_index: Option<usize>;
Please comment because it's super far away from the `if`:
```rust
// sequence >= oldest_seq_num
```

2018-09-28 03:16 UTC, AaronM04 commented
Unit test names are wack bruh

2018-09-28 03:25 UTC, AaronM04 commented on src/net.rs
> +    fn is_seq_about_to_wrap(&self, buffer_wrap_index: Option<usize>, sequence: u64, oldest_seq_num: u64, newest_seq_num: u64) -> bool {
Also please rename to `will_seq_cause_a_wrap`! :smile:

2018-10-04 05:07 UTC, Manghi commented on src/net.rs
> +    /// Sequence must be >=, or <, what we're comparing against. Cannot have wrapped yet.
😓 lol there's a secret third possibility which exists in our imagination. Clarified comment in next commit.

2018-10-04 05:08 UTC, Manghi commented on src/net.rs
> +    fn is_seq_sufficiently_far_away(&self, a: u64, b: u64) -> bool {
I don't have or anticipate a use case where I'd need them to be `mut` but I like your suggestion otherwise.

2018-10-09 03:20 UTC, AaronM04 commented on src/net.rs
> +            && self.is_seq_sufficiently_far_away(sequence, newest_seq_num)
so much simpler :100:

2018-10-09 03:23 UTC, AaronM04 approved these changes
Looks good! Merging

2018-10-09 03:23 UTC, merged